# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 05:22
from __future__ import unicode_literals

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(help_text='Email Personal.', max_length=100, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(help_text='Personal Info.', max_length=150)),
                ('last_name', models.CharField(help_text='Personal Info.', max_length=150)),
                ('status', models.CharField(blank=True, choices=[('ACTIVATED', 'ACTIVATED'), ('DEACTIVATED', 'DEACTIVATED'), ('BANNED', 'BANNED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default='PENDING', help_text='User status', max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'myuser',
            },
        ),
    ]
