# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-created']},
        ),
    ]
