# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20170528_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
    ]
