# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_remove_myuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date joined'),
        ),
    ]
